# Copyright (c) 2024 Paulo Cachim
# SPDX-License-Identifier: MIT

"""Eurocode 3 - Design of steel structures.

This module provides classes and functions for Eurocode 3 steel design.
It includes properties for different steel grades and types, profile classes
(I, CHS, RHS, SHS), bolts, welds, and connection checks.
"""

from eurocodepy import dbase as dbase
from eurocodepy.ec3 import (
    classification as classification,
    materials as materials,
    uls as uls,
)
from eurocodepy.ec3.classification import (
    SectionClass as SectionClass,
    ClassificationResult as ClassificationResult,
    EffectiveProperties as EffectiveProperties,
    epsilon as epsilon,
    classify_section as classify_section,
    classify_internal_part as classify_internal_part,
    classify_outstand_part as classify_outstand_part,
    classify_chs_part as classify_chs_part,
    effective_properties as effective_properties,
)
from eurocodepy.ec3.uls import (
    MemberInput as MemberInput,
    MemberCheckResult as MemberCheckResult,
    eurocode3_member_check as eurocode3_member_check,
    member_check_profile as member_check_profile,
    SectionForces as SectionForces,
    SectionResistanceInput as SectionResistanceInput,
    SectionResistanceResult as SectionResistanceResult,
    eurocode3_section_check as eurocode3_section_check,
    section_check_profile as section_check_profile,
)
from eurocodepy.ec3.materials import (
    BoltGrade as BoltGrade,
    Bolt as Bolt,
    BoltGrades as BoltGrades,
    BoltsEnum as BoltsEnum,
    Steel as Steel,
    SteelEnum as SteelEnum,
    SteelSection as SteelSection,
    SteelPlate as SteelPlate,
    BoltedConnection as BoltedConnection,
    PinnedConnection as PinnedConnection,
    PinnedConnectionDouble as PinnedConnectionDouble,
    ProfileCHS as ProfileCHS,
    ProfileI as ProfileI,
    ProfileRHS as ProfileRHS,
    ProfileSHS as ProfileSHS,
    ProfilesI as ProfilesI,
    ProfilesCHS as ProfilesCHS,
    ProfilesRHS as ProfilesRHS,
    ProfilesSHS as ProfilesSHS,
    ProfilesCHSEnum as ProfilesCHSEnum,
    ProfilesIEnum as ProfilesIEnum,
    ProfilesRHSEnum as ProfilesRHSEnum,
    ProfilesSHSEnum as ProfilesSHSEnum,
    Weld as Weld,
    WeldConnection as WeldConnection,
    WeldTypeEnum as WeldTypeEnum,
)

__all__ = [
    "dbase",
    "classification",
    "materials",
    "uls",
    "SectionClass",
    "ClassificationResult",
    "EffectiveProperties",
    "epsilon",
    "classify_section",
    "classify_internal_part",
    "classify_outstand_part",
    "classify_chs_part",
    "effective_properties",
    "MemberInput",
    "MemberCheckResult",
    "eurocode3_member_check",
    "member_check_profile",
    "SectionForces",
    "SectionResistanceInput",
    "SectionResistanceResult",
    "eurocode3_section_check",
    "section_check_profile",
    "BoltGrade",
    "Bolt",
    "BoltGrades",
    "BoltsEnum",
    "Steel",
    "SteelEnum",
    "SteelSection",
    "SteelPlate",
    "BoltedConnection",
    "PinnedConnection",
    "PinnedConnectionDouble",
    "ProfileCHS",
    "ProfileI",
    "ProfileRHS",
    "ProfileSHS",
    "ProfilesI",
    "ProfilesCHS",
    "ProfilesRHS",
    "ProfilesSHS",
    "ProfilesCHSEnum",
    "ProfilesIEnum",
    "ProfilesRHSEnum",
    "ProfilesSHSEnum",
    "Weld",
    "WeldConnection",
    "WeldTypeEnum",
]
