# Copyright (c) 2024 Paulo Cachim
# SPDX-License-Identifier: MIT

"""Eurocode 2: Design of concrete structures.

This module provides classes and functions for Eurocode 2 concrete design.
It includes properties for different concrete grades and types, as well as calculations
for serviceability and ultimate limit states.
"""

from eurocodepy.ec2.materials import (
    A400NR as A400NR,
    A500NR as A500NR,
    A500EL as A500EL,
    A400NRSD as A400NRSD,
    A500NRSD as A500NRSD,
    B400A as B400A,
    B400B as B400B,
    B400C as B400C,
    B500A as B500A,
    B500B as B500B,
    B500C as B500C,
    B600A as B600A,
    B600B as B600B,
    B600C as B600C,
    B700A as B700A,
    B700B as B700B,
    B700C as B700C,
    Bar as Bar,
    BarLayout as BarLayout,
    BarSizes as BarSizes,
    Bundle as Bundle,
    C20_25 as C20_25,
    C25_30 as C25_30,
    C30_37 as C30_37,
    C35_45 as C35_45,
    C40_50 as C40_50,
    C45_55 as C45_55,
    C50_60 as C50_60,
    C55_67 as C55_67,
    C60_75 as C60_75,
    C70_85 as C70_85,
    C80_95 as C80_95,
    C90_105 as C90_105,
    Concrete as Concrete,
    ConcreteClass as ConcreteClass,
    ConcreteGrades as ConcreteGrades,
    CreepParams as CreepParams,
    GammaC as GammaC,
    GammaCT as GammaCT,
    GammaP as GammaP,
    GammaS as GammaS,
    Prestress as Prestress,
    PrestressClass as PrestressClass,
    Reinforcement as Reinforcement,
    ReinforcementClass as ReinforcementClass,
    ReinforcementGrades as ReinforcementGrades,
    ShrinkStrainParams as ShrinkStrainParams,
    beta_cc as beta_cc,
    beta_ce as beta_ce,
    calc_creep_coef as calc_creep_coef,
    calc_shrink_strain as calc_shrink_strain,
    cemprops as cemprops,
    get_concrete as get_concrete,
    get_reinforcement as get_reinforcement,
)
from eurocodepy.ec2 import (
    fire as fire,
    sls as sls,
    uls as uls,
)
from eurocodepy.ec2.sls import (
    creep as creep,
    shrinkage as shrinkage,
)
from eurocodepy.ec2.sls.creep import creep_coef as creep_coef
from eurocodepy.ec2.sls.shrinkage import shrink_strain as shrink_strain
from eurocodepy.ec2.uls import (
    beam as beam,
    shear as shear,
    shell as shell,
)
from eurocodepy.ec2.uls.beam import (
    calc_asl as calc_asl,
    calc_mrd as calc_mrd,
    get_bend_params as get_bend_params,
)
from eurocodepy.ec2.uls.punch import (
    calc_perimeters as calc_perimeters,
    calc_vedp as calc_vedp,
    calc_vrdcminp as calc_vrdcminp,
    calc_vrdcp as calc_vrdcp,
)
from eurocodepy.ec2.uls.shear import (
    calc_asws as calc_asws,
    calc_vrd as calc_vrd,
    calc_vrdc as calc_vrdc,
    calc_vrdmax as calc_vrdmax,
)
from eurocodepy.ec2.uls.shell import (
    calc_reinf_plane as calc_reinf_plane,
    calc_reinf_shell as calc_reinf_shell,
)

__all__ = [
    "A400NR",
    "A500NR",
    "A500EL",
    "A400NRSD",
    "A500NRSD",
    "B400A",
    "B400B",
    "B400C",
    "B500A",
    "B500B",
    "B500C",
    "B600A",
    "B600B",
    "B600C",
    "B700A",
    "B700B",
    "B700C",
    "Bar",
    "BarLayout",
    "BarSizes",
    "Bundle",
    "C20_25",
    "C25_30",
    "C30_37",
    "C35_45",
    "C40_50",
    "C45_55",
    "C50_60",
    "C55_67",
    "C60_75",
    "C70_85",
    "C80_95",
    "C90_105",
    "Concrete",
    "ConcreteClass",
    "ConcreteGrades",
    "CreepParams",
    "GammaC",
    "GammaCT",
    "GammaP",
    "GammaS",
    "Prestress",
    "PrestressClass",
    "Reinforcement",
    "ReinforcementClass",
    "ReinforcementGrades",
    "ShrinkStrainParams",
    "beta_cc",
    "beta_ce",
    "calc_creep_coef",
    "calc_shrink_strain",
    "cemprops",
    "get_concrete",
    "get_reinforcement",
    "fire",
    "sls",
    "uls",
    "creep",
    "shrinkage",
    "creep_coef",
    "shrink_strain",
    "beam",
    "shear",
    "shell",
    "calc_asl",
    "calc_mrd",
    "get_bend_params",
    "calc_perimeters",
    "calc_vedp",
    "calc_vrdcminp",
    "calc_vrdcp",
    "calc_asws",
    "calc_vrd",
    "calc_vrdc",
    "calc_vrdmax",
    "calc_reinf_plane",
    "calc_reinf_shell",
]
