site_name: eurocodepy documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - tutorials.md
  - Modules: 
    - EC1: modules/ec1.md 
    - EC7: modules/ec7.md 
  - Reference: reference.md
  - Background: explanation.md
  - copyright.md